-- Real local Postgres authorization and lifecycle contracts; all data rolls back.
begin;
select no_plan();
update private.room_kind_features set enabled=false;
insert into auth.users(id, is_anonymous, raw_user_meta_data) values
 ('28200000-0000-4000-8000-000000000001',false,'{"display_name":"Personal owner"}'),
 ('28200000-0000-4000-8000-000000000002',false,'{"display_name":"Another account"}'),
 ('28200000-0000-4000-8000-000000000003',true,'{"display_name":"Anonymous account"}');
set local role authenticated;
select set_config('request.jwt.claim.sub','28200000-0000-4000-8000-000000000001',true);
select throws_ok($$select public.open_personal_room()$$,'42501','Personal rooms are not enabled','direct RPC obeys default-off database gate');
reset role;
update private.room_kind_features set enabled=true;
set local role anon;
select throws_ok($$select public.open_personal_room()$$,'42501',null,'signed-out callers cannot create');
set local role authenticated;
select set_config('request.jwt.claim.sub','28200000-0000-4000-8000-000000000003',true);
select throws_ok($$select public.open_personal_room()$$,'42501','An active account is required','anonymous Auth is not an eligible account');
select set_config('request.jwt.claim.sub','28200000-0000-4000-8000-000000000001',true);
reset role;
create function pg_temp.fail_personal_settings() returns trigger language plpgsql as $$
begin raise exception 'Synthetic settings failure'; end $$;
create trigger qa_fail_settings before insert on public.room_settings for each row execute function pg_temp.fail_personal_settings();
set local role authenticated;
select throws_ok($$select public.open_personal_room()$$,'P0001','Synthetic settings failure','partial creation aborts when settings fail');
reset role;
select is((select count(*)::int from public.rooms where owner_user_id='28200000-0000-4000-8000-000000000001'),0,'failed transaction leaves no orphan room');
select is((select count(*)::int from public.room_members where user_id='28200000-0000-4000-8000-000000000001'),0,'failed transaction leaves no orphan membership');
drop trigger qa_fail_settings on public.room_settings;
set local role authenticated;
select set_config('test.personal_room_id',public.open_personal_room()::text,true);
select is(public.open_personal_room()::text,current_setting('test.personal_room_id'),'repeat entry returns same room');
select is((select count(*)::int from public.rooms where room_kind='personal'),1,'one visible room');
select is((select mode from public.rooms where room_kind='personal'),'listen','first creation defaults to Listen');
select is((select count(*)::int from public.room_members where room_id=current_setting('test.personal_room_id')::uuid),1,'one owner membership');
select is((select count(*)::int from public.room_settings where room_id=current_setting('test.personal_room_id')::uuid),1,'settings created atomically');
select throws_ok($$insert into public.rooms(owner_user_id,room_kind,name,invite_code,invite_token_hash) values(auth.uid(),'personal','Bypass','BYPASS','bypass')$$,'42501',null,'direct authenticated INSERT cannot bypass RPC');
select throws_ok($$update public.rooms set status='closed' where room_kind='personal'$$,'42501',null,'direct owner close prohibited');
select throws_ok($$insert into public.room_members(room_id,user_id,display_name) values(current_setting('test.personal_room_id')::uuid,'28200000-0000-4000-8000-000000000002','Other')$$,'23514',null,'owner cannot invite foreign member');
select lives_ok($$insert into public.member_permissions(room_id,user_id,can_add_queue) values(current_setting('test.personal_room_id')::uuid,auth.uid(),true)$$,'owner permission rows remain usable');
select lives_ok($$insert into public.queue_items(room_id,source_type,source_url,position,added_by_user_id) values(current_setting('test.personal_room_id')::uuid,'direct','https://example.invalid/personal.mp4',0,auth.uid())$$,'owner queue writes allowed');
select set_config('request.jwt.claim.sub','28200000-0000-4000-8000-000000000002',true);
select is((select count(*)::int from public.rooms where room_kind='personal'),0,'unrelated account cannot discover room');
select is((select count(*)::int from public.room_members where room_id=current_setting('test.personal_room_id')::uuid),0,'membership data private');
select is((select count(*)::int from public.queue_items where room_id=current_setting('test.personal_room_id')::uuid),0,'queue data private');
select is((select count(*)::int from public.room_settings where room_id=current_setting('test.personal_room_id')::uuid),0,'settings data private');
select throws_ok($$insert into public.room_members(room_id,user_id,display_name) values(current_setting('test.personal_room_id')::uuid,auth.uid(),'Self join')$$,'23514',null,'existing self-join policy cannot bypass Personal guard');
select throws_ok($$insert into public.queue_items(room_id,source_type,source_url,position,added_by_user_id) values(current_setting('test.personal_room_id')::uuid,'direct','https://example.invalid/attack.mp4',1,auth.uid())$$,'42501',null,'unrelated queue insert denied');
reset role;
select throws_ok($$insert into public.guest_identities(room_id,display_name,token_hash) values(current_setting('test.personal_room_id')::uuid,'Stale guest','stale')$$,'23514',null,'privileged guest path also rejected');
select throws_ok($$delete from public.room_members where room_id=current_setting('test.personal_room_id')::uuid$$,'23514',null,'permanent membership cannot be removed');
select throws_ok($$update public.rooms set owner_user_id='28200000-0000-4000-8000-000000000002' where id=current_setting('test.personal_room_id')::uuid$$,'23514',null,'ownership immutable');
select throws_ok($$update public.rooms set room_kind='legacy' where id=current_setting('test.personal_room_id')::uuid$$,'23514',null,'cannot turn Personal into invite room');
update public.rooms set mode='watch',is_saved=false,idle_deadline_at=now()-interval '1 day',last_active_at=now()-interval '1 day' where id=current_setting('test.personal_room_id')::uuid;
select ok((select idle_deadline_at is null from public.rooms where id=current_setting('test.personal_room_id')::uuid),'unsaved Personal has no idle deadline');
select private.close_idle_unsaved_rooms(now()+interval '30 days');
select is((select status from public.rooms where id=current_setting('test.personal_room_id')::uuid),'open','Personal survives SQL cleanup without star');
set local role authenticated;
select set_config('request.jwt.claim.sub','28200000-0000-4000-8000-000000000001',true);
select is(public.open_personal_room()::text,current_setting('test.personal_room_id'),'same ID after cleanup');
select is((select mode from public.rooms where room_kind='personal'),'watch','resume preserves chosen mode');
select is((select count(*)::int from public.queue_items where room_id=current_setting('test.personal_room_id')::uuid),1,'resume preserves queue');
reset role;
update public.rooms set status='closed',close_reason='idle_timeout' where id=current_setting('test.personal_room_id')::uuid;
set local role authenticated;
select is(public.open_personal_room()::text,current_setting('test.personal_room_id'),'safe idle closure resumes original room');
reset role;
update public.rooms set status='closed',close_reason='manual_cleanup' where id=current_setting('test.personal_room_id')::uuid;
set local role authenticated;
select throws_ok($$select public.open_personal_room()$$,'42501',null,'administrative closure cannot be bypassed');
reset role;
select is((select count(*)::int from public.rooms where owner_user_id='28200000-0000-4000-8000-000000000001'),1,'blocked resume never creates a duplicate');
update public.profiles set account_status='disabled' where id='28200000-0000-4000-8000-000000000001';
set local role authenticated;
select is((select count(*)::int from public.rooms where room_kind='personal'),0,'disabled owner loses row visibility');
select throws_ok($$select public.open_personal_room()$$,'42501',null,'disabled owner cannot resume');
reset role;
select lives_ok($$delete from auth.users where id='28200000-0000-4000-8000-000000000001'$$,'account deletion cleans Personal atomically');
select is((select count(*)::int from public.rooms where id=current_setting('test.personal_room_id')::uuid),0,'no ownerless room remains');
select * from finish();
rollback;
