-- TASK-030 reliability. Synthetic lease state only; all changes roll back.
begin;
create schema if not exists extensions;
create extension if not exists pgtap with schema extensions;
grant usage on schema extensions to service_role,anon,authenticated;
set local search_path = public, extensions;
select no_plan();
select has_function('public','claim_recommendation_delivery',array[]::text[],'delivery claim capability exists');
select has_function('public','finish_recommendation_delivery',array['uuid','text','integer','bigint'],'delivery completion capability exists');
select ok((select relrowsecurity from pg_class where oid='private.recommendation_delivery'::regclass),'delivery lease enables RLS');
select ok(not has_table_privilege('anon','private.recommendation_delivery','SELECT'),'anonymous cannot read delivery state');
select ok(not has_table_privilege('authenticated','private.recommendation_delivery','SELECT'),'account cannot inspect global delivery state');
select ok(not has_table_privilege('authenticated','private.recommendation_delivery','UPDATE'),'account cannot change delivery state');
select ok(not has_table_privilege('anon','private.recommendation_delivery','INSERT'),'anonymous cannot create a lease');
select ok(not has_table_privilege('authenticated','private.recommendation_delivery','DELETE'),'account cannot delete a lease');
select ok(not has_function_privilege('anon','public.claim_recommendation_delivery()','EXECUTE'),'anonymous cannot start delivery');
select ok(not has_function_privilege('authenticated','public.claim_recommendation_delivery()','EXECUTE'),'account cannot start global delivery');
select ok(not has_function_privilege('anon','public.finish_recommendation_delivery(uuid,text,integer,bigint)','EXECUTE'),'anonymous cannot finish delivery');
select ok(not has_function_privilege('authenticated','public.finish_recommendation_delivery(uuid,text,integer,bigint)','EXECUTE'),'account cannot finish delivery');
select ok(has_function_privilege('service_role','public.claim_recommendation_delivery()','EXECUTE'),'service can claim delivery');
select ok(has_function_privilege('service_role','public.finish_recommendation_delivery(uuid,text,integer,bigint)','EXECUTE'),'service can finish delivery');
set local role anon;
select throws_ok('select public.claim_recommendation_delivery()','42501',null,'anonymous execution is denied');
reset role;
set local role authenticated;
select throws_ok($$select public.finish_recommendation_delivery('03000000-0000-4000-8000-000000000001','empty',0)$$,'42501',null,'account execution is denied');
reset role;

update private.recommendation_delivery set lease_token=null,lease_until=null,next_run_at=now()-interval '1 second';
create temporary table delivery_claims(label text primary key, token uuid);
grant all on delivery_claims to service_role;
set local role service_role;
insert into delivery_claims values('first',public.claim_recommendation_delivery());
select ok((select token is not null from delivery_claims where label='first'),'idle service claims delivery');
select is(public.claim_recommendation_delivery(),null::uuid,'second claim is excluded while lease is live');
reset role;
select ok((select lease_until between statement_timestamp()+interval '115 seconds' and statement_timestamp()+interval '125 seconds' from private.recommendation_delivery),'claim lease is bounded to 120 seconds');
select ok((select last_started_at is not null from private.recommendation_delivery),'start timestamp is recorded');
select is(public.finish_recommendation_delivery('03000000-0000-4000-8000-000000000099','empty',0),false,'wrong token cannot finish active claim');
select throws_ok($$select public.finish_recommendation_delivery((select token from delivery_claims where label='first'),'unknown',0)$$,'22023',null,'unknown outcome is rejected');
select throws_ok($$select public.finish_recommendation_delivery((select token from delivery_claims where label='first'),null,0)$$,'22023',null,'missing outcome is rejected');
select throws_ok($$select public.finish_recommendation_delivery((select token from delivery_claims where label='first'),'empty',null)$$,'22023',null,'missing processed count is rejected');
select throws_ok($$select public.finish_recommendation_delivery((select token from delivery_claims where label='first'),'partial',-1)$$,'22023',null,'negative processed count is rejected');
select throws_ok($$select public.finish_recommendation_delivery((select token from delivery_claims where label='first'),'partial',2001)$$,'22023',null,'processed count above pump maximum is rejected');

update private.recommendation_delivery set lease_until=now()-interval '1 second';
select is(public.finish_recommendation_delivery((select token from delivery_claims where label='first'),'empty',0),false,'expired claim cannot publish success');
insert into delivery_claims values('replacement',public.claim_recommendation_delivery());
select ok((select token is not null and token<>(select token from delivery_claims where label='first') from delivery_claims where label='replacement'),'expired lease is reclaimed with a different token');
select is(public.finish_recommendation_delivery((select token from delivery_claims where label='first'),'failed',0),false,'stale worker cannot clear replacement claim');
select is((select lease_token from private.recommendation_delivery),(select token from delivery_claims where label='replacement'),'replacement claim survives stale finish');
select is(public.finish_recommendation_delivery((select token from delivery_claims where label='replacement'),'partial',2000,1726000000000),true,'current claim may report bounded partial progress');
select is((select last_status from private.recommendation_delivery),'partial','partial status is observable');
select is((select last_processed from private.recommendation_delivery),2000,'processed count is retained');
select is((select oldest_pending_ms from private.recommendation_delivery),1726000000000::bigint,'oldest pending timestamp is retained');
select ok((select lease_token is null and lease_until is null and last_finished_at is not null from private.recommendation_delivery),'successful finish releases lease and records completion');
select ok((select next_run_at between statement_timestamp()+interval '9 seconds' and statement_timestamp()+interval '11 seconds' from private.recommendation_delivery),'partial success has a ten-second cooldown');
select is(public.claim_recommendation_delivery(),null::uuid,'cooldown prevents immediately repeating partial pump');
select is(public.finish_recommendation_delivery((select token from delivery_claims where label='replacement'),'empty',0),false,'finished token cannot alter progress again');

update private.recommendation_delivery set next_run_at=now()-interval '1 second';
insert into delivery_claims values('failure',public.claim_recommendation_delivery());
select is(public.finish_recommendation_delivery((select token from delivery_claims where label='failure'),'failed',100,1726000000000),true,'failed pump preserves confirmed progress');
select is((select last_status from private.recommendation_delivery),'failed','failure is observable');
select ok((select next_run_at between statement_timestamp()+interval '29 seconds' and statement_timestamp()+interval '31 seconds' from private.recommendation_delivery),'failure has a thirty-second retry cooldown');
select is(public.claim_recommendation_delivery(),null::uuid,'failure backoff prevents immediate retry storm');
update private.recommendation_delivery set next_run_at=now()-interval '1 second';
insert into delivery_claims values('empty',public.claim_recommendation_delivery());
select is(public.finish_recommendation_delivery((select token from delivery_claims where label='empty'),'empty',0),true,'retry can complete with an empty queue');
select is((select oldest_pending_ms from private.recommendation_delivery),null::bigint,'empty completion clears obsolete pending age');
select is((select count(*)::integer from private.recommendation_delivery),1,'delivery keeps exactly one global state row');
select * from finish();
rollback;
