begin;
create extension if not exists pgtap with schema extensions;
select plan(14);
select has_column('public','rooms','room_kind','rooms carry a durable room kind');
select is((select count(*)::int from public.rooms where invite_code like 'QA28%' and room_kind='legacy'),4,'all historical room states backfilled to Legacy');
select lives_ok($$insert into public.rooms(name,invite_code,invite_token_hash) values ('Old client','QA28OLD','fixture-old-client')$$,'old inserts omit room kind');
select is((select room_kind from public.rooms where invite_code='QA28OLD'),'legacy','omitted kind defaults to Legacy');
select throws_ok($$update public.rooms set room_kind='personal' where invite_code='QA28S'$$,'23514',null,'Legacy cannot be converted to Personal');
select throws_ok($$update public.rooms set room_kind='shared' where invite_code='QA28S'$$,'23514',null,'Shared remains disabled');
select throws_ok($$update public.rooms set room_kind='themed' where invite_code='QA28S'$$,'23514',null,'Themed remains disabled');
select throws_ok($$update public.rooms set room_kind='temporary' where invite_code='QA28S'$$,'23514',null,'Temporary remains disabled');
select throws_ok($$update public.rooms set room_kind='unknown' where invite_code='QA28S'$$,'23514',null,'unknown kinds rejected');
select throws_ok($$update public.rooms set room_kind=null where invite_code='QA28S'$$,'23514',null,'null kind rejected');
select is((select room_kind from public.rooms where invite_code='QA28S'),'legacy','failed mutations preserve Legacy kind');
select throws_ok($$insert into public.rooms(name,invite_code,invite_token_hash,room_kind) values ('Forged','QA28BAD','fixture-bad','personal')$$,'23514',null,'new-kind insert is rejected');
set local role authenticated;
select set_config('request.jwt.claim.sub','28000000-0000-4000-8000-000000000001',true);
select throws_ok($$update public.rooms set room_kind='personal' where invite_code='QA28S'$$,'23514',null,'authenticated owner cannot convert room kind');
select lives_ok($$update public.rooms set mode='watch' where invite_code='QA28S'$$,'existing host mode changes remain permitted');
reset role;
select * from finish();
rollback;
