begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,is_anonymous,raw_user_meta_data) values
 ('28400000-0000-4000-8000-000000000001',false,'{"display_name":"Shared owner"}'),
 ('28400000-0000-4000-8000-000000000002',false,'{"display_name":"Shared friend"}'),
 ('28400000-0000-4000-8000-000000000003',false,'{"display_name":"Outsider"}');
set local role authenticated;
select set_config('request.jwt.claim.sub','28400000-0000-4000-8000-000000000001',true);
-- The test controls the gate even when local browser QA has enabled it.
reset role;
update private.room_kind_features set enabled=false where room_kind='shared';
set local role authenticated;
select throws_ok($$select public.create_shared_room('Disabled','28400000-0000-4000-8000-000000000011')$$,'42501',null,'database gate blocks direct RPC creation');
reset role;
update private.room_kind_features set enabled=true where room_kind='shared';
set local role authenticated;
select set_config('request.jwt.claim.sub','28400000-0000-4000-8000-000000000001',true);
select throws_ok($$insert into public.rooms(owner_user_id,room_kind,name,invite_code,invite_token_hash) values(auth.uid(),'shared','Bypass','284-bypass','hash')$$,'42501',null,'direct inserts cannot bypass creation RPC');
select lives_ok($$select public.create_shared_room('QA Shared','28400000-0000-4000-8000-000000000010')$$,'eligible owner creates Shared atomically');
select set_config('test.shared',public.create_shared_room('QA Shared','28400000-0000-4000-8000-000000000010')::text,true);
select is((select count(*)::int from public.rooms where room_kind='shared'),1,'retry returns one room');
select is((select count(*)::int from public.room_members where room_id=current_setting('test.shared')::uuid),1,'one owner membership');
select set_config('test.invite',(select invite_code from public.rooms where id=current_setting('test.shared')::uuid),true);
select is((public.shared_room_context(current_setting('test.shared')::uuid)->>'contribute')::boolean,false,'owner also starts without learning consent');
select set_config('request.jwt.claim.sub','28400000-0000-4000-8000-000000000002',true);
select is((select count(*)::int from public.rooms where id=current_setting('test.shared')::uuid),0,'unapproved account cannot read room');
select throws_ok($$select public.request_shared_membership(current_setting('test.shared')::uuid,'wrong')$$,'42501',null,'invalid invitation denied');
select is(public.request_shared_membership(current_setting('test.shared')::uuid,current_setting('test.invite')),'pending','invite creates request, not admission');
select is(public.request_shared_membership(current_setting('test.shared')::uuid,current_setting('test.invite')),'pending','duplicate device requests are idempotent');
select is((select count(*)::int from public.room_members where room_id=current_setting('test.shared')::uuid),0,'pending request sees no room members');
select throws_ok($$insert into public.room_members(room_id,user_id,display_name,role) values(current_setting('test.shared')::uuid,auth.uid(),'Forged','guest')$$,'42501',null,'pending account cannot self-admit');
select throws_ok($$select public.set_room_learning_consent(current_setting('test.shared')::uuid,true,true)$$,'42501',null,'pending account cannot grant learning consent');
select throws_ok($$select public.decide_shared_membership(current_setting('test.shared')::uuid,auth.uid(),true)$$,'42501',null,'requester cannot approve themselves');
select set_config('request.jwt.claim.sub','28400000-0000-4000-8000-000000000001',true);
select lives_ok($$select public.decide_shared_membership(current_setting('test.shared')::uuid,'28400000-0000-4000-8000-000000000002',true)$$,'owner approves friend');
select set_config('request.jwt.claim.sub','28400000-0000-4000-8000-000000000002',true);
select is((select count(*)::int from public.rooms where id=current_setting('test.shared')::uuid),1,'approved account can return without invitation');
select set_config('test.member',(select id::text from public.room_members where room_id=current_setting('test.shared')::uuid and user_id=auth.uid()),true);
select is((public.shared_room_context(current_setting('test.shared')::uuid)->>'individual')::boolean,false,'approval does not enable individual learning');
select is(jsonb_array_length(public.shared_room_context(current_setting('test.shared')::uuid)->'members'),0,'member cannot inspect approval roster');
select throws_ok($$update public.room_members set role='host' where room_id=current_setting('test.shared')::uuid and user_id=auth.uid()$$,'42501',null,'member cannot promote own role');
select throws_ok($$update public.room_members set id=gen_random_uuid() where room_id=current_setting('test.shared')::uuid and user_id=auth.uid()$$,'42501',null,'member cannot rewrite durable identity');
select throws_ok($$delete from public.room_members where room_id=current_setting('test.shared')::uuid and user_id=auth.uid()$$,'42501',null,'direct delete is not granted');
select is((select count(*)::int from public.room_members where room_id=current_setting('test.shared')::uuid and user_id=auth.uid()),1,'direct delete cannot turn Leave into membership deletion');
select lives_ok($$select public.set_room_learning_consent(current_setting('test.shared')::uuid,true,false)$$,'member controls independent consent');
select is((public.shared_room_context(current_setting('test.shared')::uuid)->>'contribute')::boolean,true,'contribution saved');
select is((public.shared_room_context(current_setting('test.shared')::uuid)->>'individual')::boolean,false,'individual consent remains off');
select set_config('request.jwt.claim.sub','28400000-0000-4000-8000-000000000001',true);
reset role;
insert into public.member_permissions(room_id,user_id,can_control_playback) values(current_setting('test.shared')::uuid,'28400000-0000-4000-8000-000000000002',true);
set local role authenticated;
select lives_ok($$select public.decide_shared_membership(current_setting('test.shared')::uuid,'28400000-0000-4000-8000-000000000002',false)$$,'owner removes return access');
select throws_ok($$select public.decide_shared_membership(current_setting('test.shared')::uuid,'28400000-0000-4000-8000-000000000002',true)$$,'55000',null,'reapproval waits for live revocation acknowledgement');
select set_config('request.jwt.claim.sub','28400000-0000-4000-8000-000000000002',true);
select is((select count(*)::int from public.rooms where id=current_setting('test.shared')::uuid),0,'removed user cannot read room');
select is(public.request_shared_membership(current_setting('test.shared')::uuid,current_setting('test.invite')),'removed','invite replay cannot undo removal');
select throws_ok($$select public.ack_shared_revocation(current_setting('test.shared')::uuid,current_setting('test.member')::uuid)$$,'42501',null,'client cannot fake live revocation ack');
reset role;
select is((select count(*)::int from public.member_permissions where room_id=current_setting('test.shared')::uuid and user_id='28400000-0000-4000-8000-000000000002'),0,'removal deletes durable permission overrides before reapproval');
select is((select count(*)::int from private.room_learning_consents where room_id=current_setting('test.shared')::uuid and user_id='28400000-0000-4000-8000-000000000002' and revoked_at is null),0,'removal closes both consent epochs');
set local role service_role;
select public.ack_shared_revocation(current_setting('test.shared')::uuid,current_setting('test.member')::uuid);
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','28400000-0000-4000-8000-000000000001',true);
select isnt(public.decide_shared_membership(current_setting('test.shared')::uuid,'28400000-0000-4000-8000-000000000002',true)::text,current_setting('test.member'),'reapproval creates a fresh membership ID');
select set_config('request.jwt.claim.sub','28400000-0000-4000-8000-000000000003',true);
select is(public.shared_room_context(current_setting('test.shared')::uuid),null::jsonb,'unknown outsider learns nothing without an invite');
select throws_ok($$select * from private.shared_memberships$$,'42501',null,'private membership decisions have no client table grant');
reset role;
update public.rooms set is_saved=false,last_active_at=now()-interval '5 days',idle_deadline_at=now()-interval '4 days' where id=current_setting('test.shared')::uuid;
select private.close_idle_unsaved_rooms(now()+interval '1 day');
select is((select status from public.rooms where id=current_setting('test.shared')::uuid),'open','Shared persists independently of star and idle');
select is((select idle_deadline_at from public.rooms where id=current_setting('test.shared')::uuid),null::timestamptz,'Shared has no idle expiry');
delete from auth.users where id='28400000-0000-4000-8000-000000000001';
select is((select count(*)::int from public.rooms where id=current_setting('test.shared')::uuid),0,'owner deletion removes Shared rather than leaving it ownerless');
select is((select count(*)::int from private.shared_memberships where room_id=current_setting('test.shared')::uuid),0,'owner deletion cascades private membership decisions');
select * from finish();rollback;
